version: '3'

volumes:
  metadata:
  deckfiles:

services:
  database:
    image: mongo
    volumes:
      - ./metadata/:/data/db
    command: mongod --quiet --logpath /dev/null

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./deckfiles/:/app/deckfiles
    ports:
      - 8080:8080
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
    env_file: .env
    ports:
      - 8081:80
    depends_on:
      - server 
