version: '3'

services:
  database:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8081:80
    depends_on:
      - server

volumes:
  mongodb_data:
