// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Deck struct {
	Subject   *string `json:"subject,omitempty"`
	Module    string  `json:"module"`
	ModuleAlt *string `json:"moduleAlt,omitempty"`
	Examiners *string `json:"examiners,omitempty"`
	Language  *string `json:"language,omitempty"`
	Semester  *string `json:"semester,omitempty"`
	Year      *int    `json:"year,omitempty"`
	Hash      string  `json:"hash"`
}

type Mutation struct {
}

type NewDeck struct {
	Subject   *string        `json:"subject,omitempty"`
	Module    string         `json:"module"`
	ModuleAlt *string        `json:"moduleAlt,omitempty"`
	Examiners *string        `json:"examiners,omitempty"`
	Language  *string        `json:"language,omitempty"`
	Semester  *string        `json:"semester,omitempty"`
	Year      *int           `json:"year,omitempty"`
	File      graphql.Upload `json:"file"`
}

type Query struct {
}
